### ISSUE TITLE
Minikube support

### ISSUE THREAD

**Issue by pyronicide** [vapor-ware/ksync#100]
It looks like there are a couple problems with minikube support. So far, the most obvious is:

```
ERRO[0000] (remote_container.go:118): rpc error: code = Unknown desc = Error response from daemon: client is newer than server (client API version: 1.25, server API version: 1.24)
```

Minikube is running docker 1.12 instead of the GKE version of 1.13. See [versioning](https://docs.docker.com/engine/api/v1.26/#section/Versioning) for some more details.

It looks like we might need to do some daemon version detection and picking of API version. I'm wondering if it is possible to just default to something like 1.6.x (1.18) and be done with it.

**Comment by mhausenblas** [comment]
I'm using minikube version: v0.21.0 and have this problem

**Comment by pyronicide** [comment]
Tested on v0.23.* and it works. There are numerous problems with v0.20 - v0.22 and so those versions won't be supported for the time being. If there's some interest, it is doable and just need some love.
