### ISSUE TITLE
Syncthing is creating odd conflicts

### ISSUE THREAD

**Issue by pyronicide** [vapor-ware/ksync#130]
Running through getting started, everything works if the local directory does not have any files. Unfortunately, if you start up with files locally (and nothing in the container has been updated), syncthing creates a `*.conflict.*` file because the files are different.

We need to have a better conflict policy in place as this behavior is pretty frustrating.

**Comment by timfallmk** [comment]
Are we not doing remounting on filesystem changes?

**Comment by pyronicide** [comment]
Nope.
