### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pyronicide** [vapor-ware/ksync#136]
- Note the presence of binaries and platform support and expand the install instructions slightly.

```
(macOS/Linux/Windows)
```

- Explain the problem a little bit better and what ksync enables you to do.
- Put an animated example together
- Add a demo video

Other suggestions:

- Add a TOC at the top
- Add some more shields (godoc, latest release) - http://shields.io/

**Comment by pyronicide** [comment]
@timfallmk any suggestions?

**Comment by timfallmk** [comment]
I hate to say it but there might need to be some higher level (marketing) fluff, hopefully minimal, to counter the common "Ok, so what?" reaction.

Document the contribution/verification for pull request steps?
