### ISSUE TITLE
Add ability to use a private repository

### ISSUE THREAD

**Issue by lad** [vapor-ware/ksync#141]
This looks like a really useful tool but we cannot use it at work because "ksync init" seems to pull from the internet by default - which we cannot do for security reasons.

Please add the ability to configure the remote location to a private container repository and please document which images we would need to mirror locally.

**Comment by timfallmk** [comment]
@lad There are a couple of components that reach out to the public internet, always to pull something. If you want to, it should be relatively easy to replace (most) of the things that are being fetched with local copies.
Here's the list of things that are currently grabbed:

**Remote**
1. The nodes in the remote cluster attempt to pull the docker image `vaporio/ksync` from [Docker Hub](https://hub.docker.com/r/vaporio/ksync/). The tag matches the release version.

**Local**
1. The local binary downloads the `syncthing` binary to it's config directory, `~/.ksync/bin/syncthing` (you should be able to use the latest stable from [the project repo](https://github.com/syncthing/syncthing) )
2. `ksync update` checks this repo for the latest release and updates it if found.

It should ultimately be configurable to skip these steps if needed. In the meantime I would recommend downloading the above manually and placing it in the expected locations. In the case of local files, they will not be redownloaded if they already exist.

For the docker image you can _also_ build it from this repo if needed.

Let me know if you have problems, I haven't tested this myself.

**Comment by grampelberg** [comment]
There's also a hidden flag to override the image to use (`ksync --image=my-repo/ksync:tag`). That'll make the remote use whatever image you've got inside your cluster.

**Comment by timfallmk** [comment]
@lad I'll mark this as closed for the moment. We might refactor in the future to make this more flexible.
