### ISSUE TITLE
One-way syncing

### ISSUE THREAD

**Issue by WesCossick** [vapor-ware/ksync#144]
It would be helpful if we could enable one-way syncing for ksync instead of bidirectional syncing. For our use case, this would be helpful to ensure folders like `node_modules/` and `vendor/` don't get synced back from the pod into our local copy.

**Comment by timfallmk** [comment]
@WesCossick Are you thinking the entire target would be one way, or certain things would be excluded? We've been playing around with using a `.gitignore` type syntax for excluding things within the path.

**Comment by WesCossick** [comment]
I think both could be useful. I'm sure some people may only want to exclude certain files/folders from being synced from the pod into the local copy.

In our case, though, we just don't have any interest in syncing files from the pod into the local copy. We're only interested in syncing files from our local machine into the minikube cluster's pods.

**Comment by grampelberg** [comment]
This doesn't solve the single direction sync problem, but it should fix your current issue (ignoring vendor/node_modules):

https://docs.syncthing.net/users/ignoring.html

**Comment by WesCossick** [comment]
That definitely helps, thanks for sharing this. An option to disable bidirectional syncing would still be awesome though.

**Comment by timfallmk** [comment]
Updates on possible implantation: https://forum.syncthing.net/t/one-way-sync-configuration/11000/4
