### ISSUE TITLE
FATAL File is not writable. It is set to r--r--r--

### ISSUE THREAD

**Issue by nigorice** [vapor-ware/ksync#151]
I'm having trouble setting up ksync, on `ksync create`, I would get the following error:

```
# on the repo folder
$ ksync watch &
$ ksync create --selector=app=app $(pwd) /some/folder
FATA[0000] File /.git/objects/02/b8590f099b6f0c225762099bf345215160c5eb is not writable. It is set to r--r--r--
```

I've also tried placing a `.stignore` file on the repo folder to no avail. Is there anything I'm missing?

**Comment by timfallmk** [comment]
@nigorice Can you share the contents of your `.stignore`?

**Comment by leonth** [comment]
I'm @nigorice 's colleague. This is the .stignore I use to reproduce this issue:

```
/.git
```

**Comment by timfallmk** [comment]
@leonth I'm thinking you might want to remove the leading slash. Git shell-globbing patterns are a bit tricky, but this is from `man .gitignore` :

>A leading slash matches the beginning of the pathname. For example, "/*.c" matches "cat-file.c" but not "mozilla-sha1/sha1.c".

**Comment by leonth** [comment]
Still the same:
```
$cat .stignore
.git

$ ksync create -l app=connexi -n nicholas $(pwd) /go/src/appname
FATA[0000] File /home/leon/goworkspace/src/appname/.git/modules/somemodule/objects/pack/pack-d759179288cb0796fdb4ff9a1c51b50cf245047f.idx is not writable. It is set to r--r--r-- 
```

**Comment by nigorice** [comment]
This is mine, stuck at `ksync create`

```
$ cat .stignore
.git/
.DS_Store
lastupdate.tmp
connexi
logserver.txt
connexi.exe*
build
analytics_log
*.log

# duplicated comments router; Beego's bug
*commentsRouter__*

.idea/
.vscode/

vendor/github.com/hashicorp/terraform/config/module/test-fixtures/
vendor/github.com/pierrec/lz4/fuzz/corpus/
vendor/**/*_test.go
vendor/**/*.png
vendor/**/*.zip
vendor/**/*.pdf
vendor/**/testdata/
```

**Comment by jstrachan** [comment]
has anyone got a `.stignore` to ignore the `.git` directory? tried all kinds of permutations and so far its never ignored

**Comment by timfallmk** [comment]
I'll ping @grampelberg here and he'll fix all life's problems.

**Comment by timfallmk** [comment]
@all please test #152  and see if this solves your issue for now (I've attached a few common format binaries here from the build).
[ksync_linux_amd64.zip](https://github.com/vapor-ware/ksync/files/1953421/ksync_linux_amd64.zip)
[ksync_darwin_amd64.zip](https://github.com/vapor-ware/ksync/files/1953422/ksync_darwin_amd64.zip)

**Comment by nigorice** [comment]
@timfallmk tried the binary you attached and I'm no longer running into the same error. Thanks.

**Comment by timfallmk** [comment]
@all released! Don't forget to `ksync upgrade` if you used the unsigned binaries above (or just want to update).

**Comment by timfallmk** [comment]
@ashahba You caught me ☺️

**Comment by ashahba** [comment]
Yes @timfallmk I'm working on integrating `Ksync` with [mlt](https://github.com/IntelAI/mlt) and this PR helps me too.
