### ISSUE TITLE
Version 0.1.5 not working anymore

### ISSUE THREAD

**Issue by mickael83** [vapor-ware/ksync#162]
I updated ksync to its last version 0.1.5 and now I'm not able to init ksync on minikube cluster. I get the following output when I run `ksync init`:

```shell
$ ksync init
==== Preflight checks ====
Cluster Config                              ✓ 
Cluster Connection                          ✓ 
Cluster Version                             ✓ 
Cluster Permissions                         ✓ 

==== Cluster Environment ====
Adding ksync to the cluster                 ✓ 
Waiting for pods to be healthy              ✓ 

==== Postflight checks ====
Cluster Service                             ✓ 
Service Health                              ✓ 
Service Version                             ✘ 
↳	There is a mismatch between the local version (0.1.5) and the cluster ().

Run 'ksync init --upgrade' to fix.
FATA[0000]  
```

Then when I run `ksync init --upgrade` I get:

```shell
$ ksync init --upgrade
==== Preflight checks ====
Cluster Config                              ✓ 
Cluster Connection                          ✓ 
Cluster Version                             ✓ 
Cluster Permissions                         ✓ 

==== Cluster Environment ====
Adding ksync to the cluster                 ✓ 
Waiting for pods to be healthy              ✓ 

==== Postflight checks ====
Cluster Service                             ✓ 
Service Health                              ✓ 
Service Version                             ✘ 
↳	There is a mismatch between the local version (0.1.5) and the cluster ().

Run 'ksync init --upgrade' to fix.
FATA[0014] 
```

Is there a step I'm missing?

**Comment by timfallmk** [comment]
I’ve been seeing this recently too, mostly on upgrades. I think the health checks get in a funky state when pods are coming up. If you used —skip-checks it should run as intended. You can the check the version to see if it was successful. The other option is to just relaunch it with ‘clean —remote’ and ‘init —remote’ since there’s no saved state remotely.

Still not sure what’s causing this.

**Comment by timfallmk** [comment]
This appears to have something to do with our CI image builds. There’s race condition that causes untagged images to be released.

@mickael83 for now you may use ‘init —upgrade —image=vaporio/ksync:0.1.5’ to force the right image.

I’ll try to fix this tomorrow.

**Comment by timfallmk** [comment]
@mickael83 This should be fixed now. Please let me know if you run into it again.

**Comment by mickael83** [comment]
@timfallmk the command `ksync init —upgrade —image=vaporio/ksync:0.1.5` fixed the issue. Thanks! Great project by the way!
