### ISSUE TITLE
add a json output option for `ksync get`

### ISSUE THREAD

**Issue by jstrachan** [vapor-ware/ksync#172]
we've added `ksync` support into [Jenkins X](https://jenkins-x.io/) and its working really well when folks use [DevPods](https://jenkins-x.io/developing/devpods/) so that all your building and running takes place in the cloud while you use your desktop IDE.

This works particularly well in the [VS Code extension](https://jenkins-x.io/developing/ide/) - opening a DevPod terminal sets up ksync behind the scenes for you.

We want to be able to query easily what the current ksync results are and we've been using `ksync get` and then parsing the text that comes back which is a little fiddly to parse; you often get an extra line with `starting` or `watching` in there; so we're [filtering out the last line and any with <= 2 columns which is a bit of a hack really](https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/sync.go#L220-L226) - there's sometimes newlines in the rows ;).

e.g. 
```
$ ksync get
        NAME                     LOCAL                           REMOTE                 STATUS           POD
+-------------------+------------------------------+---------------------------------+----------+-------------------+
  jstrachan-jx-base   /workspace/java/builder-base   /home/jenkins/java/builder-base
                                                                                       watching   jstrachan-jx-base
  jstrachan-maven     /tmp/cheese/hipster3           /home/tmp/cheese/hipster3
                                                                                       starting   jstrachan-maven
```

I wonder if we could have a simple `json` output CLI option for `ksync get` so its easier to parse what actual specs really are created currently so we can more reliably reason about which ones need to be created/deleted?

Something like...
```json
$ ksync get -ojson
[
  { 
    "name": "foo",
    "local": "local",
    "remote": ....
  }
]
```

**Comment by ashahba** [comment]
@timfallmk and @jstrachan I think that'll great addition to the `Ksync` as I'm working to incorporate it into [MLT](https://github.com/IntelAI/mlt) and I'm facing the same challenge of manually reading the output and parsing it into some format like `json` and then query from there.

So basically having an option for `ksync get` like `--table`, or `--json` would be great.

**Comment by timfallmk** [comment]
Interesting idea. The -q output might help you a bit in the meantime, but I’ve been wanting to add output formatting options to all commands to a while.

I’ll trade that work for an Atom.io extension instead of VS Code 😛

**Comment by timfallmk** [comment]
@jstrachan I should also add that the newlines are intentional (I ran into that myself, but @grampelberg  did the right thing). I _think_ it's the provide cleaner output should the fields run long.

**Comment by grampelberg** [comment]
I'm a huge +1 to this. Should probably follow the kubectl pattern of `-o=json`. 

@jstrachan @ashahba mind posting some sample JSON for what you're thinking of? 

Also, what's a better serialization format: YAML, JSON, ....?

**Comment by timfallmk** [comment]
I vote for at least yaml, json, pretty.

**Comment by ashahba** [comment]
Thanks @timfallmk and @grampelberg 
How about this one for `JSON`:


```json
{
   "simple-sol":{
      "LOCAL":"source_code/IntelAI/mlt/my-hello-world",
      "REMOTE":"/src/app",
      "STATUS":"watching",
      "POD":"my-hello-world-e64fe2fc",
      "CONTAINER":"my-hello-world:latest"
   },
   "moderate-sol":{
      "LOCAL":"source_code/IntelAI/mlt/my-hello-world-sync",
      "REMOTE":"/src/app",
      "STATUS":"starting",
      "POD":"my-hello-world-sync-e64fe2fc",
      "CONTAINER":"my-hello-world-sync:latest"
   }
}
```

and this for `YAML`:
```yaml
--- 
- 
  simple-sol: 
    CONTAINER: "my-hello-world:latest"
    LOCAL: source_code/IntelAI/mlt/my-hello-world
    POD: my-hello-world-e64fe2fc
    REMOTE: /src/app
    STATUS: watching
- 
  moderate-sol: 
    CONTAINER: "my-hello-world-sync:latest"
    LOCAL: source_code/IntelAI/mlt/my-hello-world-sync
    POD: my-hello-world-sync-e64fe2fc
    REMOTE: /src/app
    STATUS: starting
```

**Comment by jstrachan** [comment]
LGTM

**Comment by timfallmk** [comment]
Question: We could use similar output formatters? https://github.com/vapor-ware/synse-cli/tree/master/pkg/formatters

**Comment by timfallmk** [comment]
Leaving some notes:
- https://github.com/buger/goterm
- https://github.com/hokaccha/go-prettyjson
- #179

**Comment by grampelberg** [comment]
I dunno if we need any pretty output (though go-prettyjson looks pretty great). Since we're just going to be using this for machines, the first version should probably just serialize the protobufs and see how it looks.

**Comment by ashahba** [comment]
@timfallmk for me it doesn't matter but if I want pretty output I go with `prettyjson`

**Comment by timfallmk** [comment]
@everyone I've added a simplistic first pass at this in 89dd3102450486cfd9c14db4e4abb46804c746cd

Let me know what you think.

A question I have so far is whether I should add a newline after squirting the output. I assume I should, but I dunno if that will really mess with anyone's Mario piping.

**Binaries attached**
[Darwin x64](https://716-105306631-gh.circle-artifacts.com/0/binaries/ksync_darwin_amd64)
[Linux x64](https://716-105306631-gh.circle-artifacts.com/0/binaries/ksync_linux_amd64)
[Windows x64](https://716-105306631-gh.circle-artifacts.com/0/binaries/ksync_windows_amd64.exe)

**Comment by ashahba** [comment]
@timfallmk my first pass looks good:
```json
{
   "items":{
      "simple-sole":{
         "details":{
            "name":"simple-sole",
            "selector":"app=e64fe2fc-a82d-4de0-acf6-50ffcc577124",
            "namespace":"ashahba",
            "localPath":"/Users/ashahba/source_code/IntelAI/mlt/my-hello-world-sync",
            "remotePath":"/src/app",
            "reload":true
         },
         "services":{
            "items":[
               {
                  "specDetails":{
                     "name":"simple-sole",
                     "selector":"app=e64fe2fc-a82d-4de0-acf6-50ffcc577124",
                     "namespace":"ashahba",
                     "localPath":"/Users/ashahba/source_code/IntelAI/mlt/my-hello-world-sync",
                     "remotePath":"/src/app",
                     "reload":true
                  },
                  "remoteContainer":{
                     "id":"eca40d3eba7aab365d3073476706a73572a0a9983b257c4179834ce3680f8e50",
                     "nodeName":"MY_CLUSTER_NAME",
                     "podName":"my-hello-world-sync-e64fe2fc-a82d-4de0-acf6-50ffcc577124-7dfzx"
                  },
                  "status":"watching"
               }
            ]
         },
         "status":"running"
      }
   }
}
```

Let me play with this a bit more and will ping you  with more feedback.
