### ISSUE TITLE
Error at "ksync init" command on windows

### ISSUE THREAD

**Issue by gadavivi** [vapor-ware/ksync#175]
i am getting this error when i am running ksync init:
```
$  .\ksync.exe init

==== Local Environment ====
Fetching extra binaries                     ✘
↳       archive/tar: invalid tar header
FATA[0007]
```

any idea why?

**Comment by timfallmk** [comment]
@gadavivi Do you have any sort of network redirection between you and the internet?

You can see what's being run here: https://github.com/vapor-ware/ksync/blob/master/pkg/syncthing/fetch.go#L50 . It's basically just pulling the latest release from github

Additionally, you can do it manually by following the [offline documentation](https://github.com/vapor-ware/ksync/blob/master/docs/offline.md)

**Comment by gadavivi** [comment]
i followed the offline documents and it solve my problem (my guess is that for windows it download the wrong file, so this is why i am getting the "archive/tar: invalid tar header" error).

also when i ran it the first time, i got this error:
` .\ksync.exe init
==== Preflight checks ====
Cluster Config                              ✓
Cluster Connection                          ✓
Cluster Version                             ✓
Cluster Permissions                         ✓

==== Cluster Environment ====
Adding ksync to the cluster                 ✓
Waiting for pods to be healthy              ✘
↳       Timed out waiting for the ksync daemonset to be healthy.`

after i ran it again it works! so maybe the timed out suppose to be greater...

**Comment by timfallmk** [comment]
Looking at the syncthing releases it looks like windows releases are packaged differently, in zip format. We'll have to fix this.

**Comment by igdianov** [comment]
Same problem here trying to `ksync init --upgrade --log-level=debug` on Windows 10:

```
DEBU[0000] initializing kubernetes client                context=
DEBU[0000] kubernetes client created                     host="https://192.168.99.138:8443"
==== Local Environment ====
DEBU[0000] fetching new syncthing binary
Fetching extra binaries                     ✘
↳       archive/tar: invalid tar header
FATA[0002]
```
