### ISSUE TITLE
Error in "ksync watch" on windows

### ISSUE THREAD

**Issue by gadavivi** [vapor-ware/ksync#176]
In windows, when running the "ksync watch" command a file named **"syncthing.pid"** is created in the user folder, after killing the process with Ctrl+c, and running the  "ksync watch" command again i am getting this error:

`FATA[0000] not supported by windows`

deleting the **"syncthing.pid"** solved the issue for now...

maybe for windows the "syncthing.pid" not suppose to be created, because the daemon option is not supported for windows...

**Comment by timfallmk** [comment]
Reference here: https://github.com/vapor-ware/ksync/blob/windows-binary-fetch/pkg/ksync/syncthing.go#L120-L121

**Comment by gadavivi** [comment]
hey,
i am getting this error after the new release:

`ERRO[0114] rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil  ContainerName= LocalPath="C:\\Users\\gadavivi\\ksync" LocalReadOnly=false Name=valid-ladybug Namespace=default Pod= Reload=true RemotePath=/code RemoteReadOnly=false Selector="app=app"`

any idea why?

**Comment by timfallmk** [comment]
Yeah. We’ve been seeing that too, so I don’t think it’s a Windows issue. I’ll open a new issue so we can investigate.
