### ISSUE TITLE
[need help] Segmentation fault when executing ksync

### ISSUE THREAD

**Issue by bilalbayasut** [vapor-ware/ksync#193]
## Expected Behavior
Firstly I run `minikube start` then `curl https://vapor-ware.github.io/gimme-that/gimme.sh | bash`.
after installing ksync just like in documentation, when typing `ksync version` the version should be appeared. 

## Actual Behavior
when I typed `ksync` the message `Segmentation fault` appears.

## Steps to Reproduce the Problem

  1. `minikube start`
  2. `curl https://vapor-ware.github.io/gimme-that/gimme.sh | bash`
  3. `ksync version`

## Specifications

  - Version: Docker version 18.03.1-ce, build 9ee9f40 and minikube version: v0.27.0
  - Platform: Linux ubuntu 18.04

**Comment by timfallmk** [comment]
@bilalbayasut could you paste a trace please?

**Comment by timfallmk** [comment]
You should see a trace dump when the segfault happens. Just copy from that point and paste here.

**Comment by bilalbayasut** [comment]
the only information in the screen was only Segmentation fault. Just that @timfallmk

**Comment by timfallmk** [comment]
@bilalbayasut Hmm, it would be hard for me to help you then. Maybe tell me a little bit more about what you're doing?

- What's your environment (OS, version, env)?
- What cluster are you connecting to?
- What command are you running that triggers the error?

**Comment by bilalbayasut** [comment]
- myos is latest LTS ubuntu
- the cluster I'm running on is minikube
- the commands that trigger the error, is `ksync` and `ksync version` , I think all commands related to ksync cause this error

**Comment by timfallmk** [comment]
I think the best way would be to start over, as it seems like you're missing a step somewhere. Try doing the following:

1. Delete the binary and anything else you downloaded
2. Go to the releases page on this repo and download the newest release for your platform (should be [this one](https://github.com/vapor-ware/ksync/releases/download/0.2.3/ksync_linux_amd64)
3. Make the binary executable (run from the directory you downloaded it to)
```shell
chmod +x ./ksync_linux_amd64
```
4. (Optional) Add the binary to your path
```shell
mv ./ksync_linux_amd64 /usr/local/bin/ksync
```
5. (Optional) Check the binary is in your path
```shell
which ksync
```
6. Execute a command
```shell
ksync doctor
```

**Comment by bilalbayasut** [comment]
Cool it works, thanks a lot @timfallmk
