### ISSUE TITLE
Provide a mechanism to get a filtered list of specs, based on a given criteria.

### ISSUE THREAD

**Issue by ashahba** [vapor-ware/ksync#200]
Currently `ksync get` dumps all specs, in fact:
```
$ ksync get -h
Get all specs.

	Based off what specs have been created, returns the current status of each spec.
```
It'll be very useful to be able to just do 
```
ksync get --name SPEC_NAME_01,SPEC_NAME_02     
```
and then dump the table for only these 2 specs.
or something like:
```
ksync get --localPath LOCAL_PATH_01,LOCAL_PATH_02
```
and then repot the table with all entries that their local is the above paths.

**Comment by timfallmk** [comment]
@ashahba This could go very quickly down a rabbit hole. Would it suffice to provide go template based filtering, or do we need something more specific?

cc: @grampelberg

**Comment by ashahba** [comment]
@timfallmk I think for this issue it's better to keep it simple and only provide support for filtering by `name` since name is a primary key and it's pretty easy to filter based on that.

We can defer supporting other queries like:
```ksync get --localPath LOCAL_PATH_01,LOCAL_PATH_02``` or even combinations like:
```
ksync get --localPath LOCAL_PATH_01,LOCAL_PATH_02 --remotePath REMOTE_PATH_01,REMOTE_PATH_02
```
for later and I can file a different ticket and possibly better crafted for what can for improvements.

**Comment by timfallmk** [comment]
I'm thinking this might be easier if it goes one of two ways:

1. Searching is done based on spec name, and only performed if an argument is supplied to `ksync get` (lets call this the simple way)
2. Fuzzy searching is done against specs based on arguments to `ksync get`. I.E. any portion of a spec that matches the given arguments will be returned (call this the fuzzy way)

Thoughts? Would it make this feature less useful?
