### ISSUE TITLE
Ksync needs syncthing.exe on Windows

### ISSUE THREAD

**Issue by jordanbuchman** [vapor-ware/ksync#201]
When running `ksync watch` (after a successful `ksync init`) in Powershell on Windows 10, the following error occurs:
```
FATA[0000] exec: "C:\\Users\\jbuchman\\.ksync\\bin\\syncthing": file does not exist
```
Renaming the file to `syncthing.exe` solves the problem.

**Comment by timfallmk** [comment]
@jordanbuchman Are you running the latest version?

**Comment by jordanbuchman** [comment]
This is the output of `ksync version`:
