### ISSUE TITLE
Fails connecting to EKS cluster

### ISSUE THREAD

**Issue by paveq** [vapor-ware/ksync#209]
Have not been able to connect to EKS cluster so far. Maybe has something to do with heptio-authenticator-aws used to connect to EKS cluster?

```
$ ~/.jx/bin/ksync init --remote --log-level=debug
DEBU[0000] initializing kubernetes client                context=
DEBU[0000] kubernetes client created                     host="https://x.sk1.us-west-2.eks.amazonaws.com"
==== Preflight checks ====
DEBU[0000] initializing kubernetes client                context=
DEBU[0000] kubernetes client created                     host="https://x.sk1.us-west-2.eks.amazonaws.com"
Cluster Config                              ✓
Cluster Connection                          ✘
↳	Unable to contact the cluster for context (). Does 'kubectl --context= cluster-info' work?
FATA[0001] Fix errors and try again.
```

Running `kubectl --context= cluster-info` does work as intended.

**Comment by dbenhur** [comment]
The [package constraint on client-go](https://github.com/vapor-ware/ksync/blob/46ad6301437ccdad344e1baab8f9a129d033b175/Gopkg.toml#L40-L42) is set to release-4.0 which I think pre-dates the support for the exec auth plugin.   Try building with a current K8s client-go.

**Comment by timfallmk** [comment]
@paveq If @dbenhur 's suggestion works for you I can update it here.

**Comment by timfallmk** [comment]
@here This is much more complicated than it seems, due to the moronic versioning practices of the k8s team. It will take some time.

**Comment by dbenhur** [comment]
@timfallmk What are the problems with the versioning scheme?  The "k8s team" is a vast open community of thousands of contributors.  If you have specific issues and concrete suggestions, I suggest you raise them with the community.  My experience with k8s has been that this is an exceptionally open project eager to make it possible to contribute and improve.  Perhaps you could take your issues with versioning to [sig-contribx](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/README.md)

**Comment by timfallmk** [comment]
Thanks @dbenhur but I'm quite familiar with them and the way they work (obviously). I find a lot of the design decisions and management to be impenetrably stupid, a classic case of "design by committee" writ large. However that list is far too long for here, off topic, and nothing anyone else doesn't complain about already.

For this specific problem:
1. Several sets of dependencies have changed.
2. K8s uses namespacing _and_ versioning at the same time
3. Their support for `dep` is nonexistent
4. They require a half million cross transient dependency overrides

To name a few.

I'm 1.5 hours into try to fix this and I haven't even gotten to the compile stage. If you want some entertainment, I suggest you bump the version of that package to the latest `release-8.0` and follow the rabbit hole.

**Comment by paveq** [comment]
@timfallmk Thanks for the update!

However I still have exact same issue with latest version. I'm trying to debug this with dlv with not much success (my breakpoints are not working), but I noticed that sometimes process goes through when running the command quickly after previous one.

```
Paavo-Pokkinen:ksync paveq$ dlv --listen=:2345 --headless=true --api-version=2 exec ./bin/ksync -- doctor
API server listening at: [::]:2345
debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-902.0.79.7
 for x86_64.
Got a connection, launched process ./bin/ksync (pid = 77165).
could not launch process: decoding dwarf section info at offset 0x0: too short
Exiting.
Paavo-Pokkinen:ksync paveq$ Extra Binaries                              ✓
Cluster Config                              ✓
Cluster Connection                          ✘
↳	Unable to contact the cluster for context (). Does 'kubectl --context= cluster-info' work?

Paavo-Pokkinen:ksync paveq$
Paavo-Pokkinen:ksync paveq$
Paavo-Pokkinen:ksync paveq$ dlv --listen=:2345 --headless=true --api-version=2 exec ./bin/ksync -- doctor
API server listening at: [::]:2345
debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-902.0.79.7
 for x86_64.
Got a connection, launched process ./bin/ksync (pid = 77169).
could not launch process: decoding dwarf section info at offset 0x0: too short
Exiting.
Paavo-Pokkinen:ksync paveq$ Extra Binaries                              ✓
Cluster Config                              ✓
Cluster Connection                          ⣯
Cluster Connection                          ⣾
Cluster Connection                          ✓
Cluster Version                             ✓
Cluster Permissions                         ✓
Cluster Service                             ✓
Service Health                              ⢿
Service Health                              ⣯
Paavo-Pokkinen:ksync paveq$
Service Health                              ⣻
Service Health                              ⣯
Service Health                              ⣽
Paavo-Pokkinen:ksync paveq$
Paavo-Pokkinen:ksync paveq$
Service Health                              ⣻
Paavo-Pokkinen:ksync paveq$
Service Health                              ⢿
Paavo-Pokkinen:ksync paveq$
Service Health                              ✓
Service Version                             ⣯
Service Version                             ⣷
Service Version                             ⣽
Service Version                             ⢿
Service Version                             ⣟
Service Version                             ✘
↳	There is a mismatch between the local version () and the cluster (0.2.4).

Run 'ksync init --upgrade' to fix.
```

**Comment by paveq** [comment]
Weirdly enough, this only happens when running with dlv. Could it be some kind of timing issue?

**Comment by paveq** [comment]
Looks like issue comes with one second timeout on line `if client.Get().Timeout(1*time.Second).Do().Error() != nil` of file kubernetes.go, which seems not to be enough for heptio authenticator. Increasing this to 5 seconds fixes the issue.

**Comment by paveq** [comment]
Been running now with timeout fix in place, and I can confirm ksync works perfectly with EKS now.
