### ISSUE TITLE
[need help] The server rejected our request for an unknown reason (get pods) and no pods name defined

### ISSUE THREAD

**Issue by bilalbayasut** [vapor-ware/ksync#214]
## Expected Behavior
1. Hi folks, I try to use ksync and I accidentally enter the wrong command in 
`ksync create --selector=app=web=tier=backend $(pwd)/web /web` and this error shows `The server rejected our request for an unknown reason (get pods)` whenever I tried to run `ksync watch --daemon`.
2. Before it happens, I can't sync my files as when I run `ksync get` I don't get pods and container name

## Actual Behavior

1. `The server rejected our request for an unknown reason (get pods)`appears
2. No pods name and container name in `ksync get`

## Steps to Reproduce the Problem

  1. `ksync init
  2. `ksync watch --daemon`
  3. `ksync create --selector=app=web=tier=backend $(pwd)/web /web`

## Specifications

  - Version: Docker version 18.03.1-ce, build 9ee9f40 and minikube version: v0.28.0
  - Platform: Linux ubuntu 18.04

**Comment by timfallmk** [comment]
@bilalbayasut A few things:
1. You'll need to specify selectors as one per flag (e.g. `--selector=app=web --selector=tier=backend`)
2. It looks like the k8s is rejecting the call to `get pods`. This could be a misconfiguration of the client. Can you run `ksync doctor` and see what it reports. Also try `kubectl get pods -l app=web -l tier=backend`.

**Comment by bilalbayasut** [comment]
Fixed, the solution I did is just to re-install ksync :smile:
