### ISSUE TITLE
`ksync init` even on a brand new GKE cluster complains about version mismatch.

### ISSUE THREAD

**Issue by ashahba** [vapor-ware/ksync#218]
Since a few days ago after I install `ksync` for the first time, and once all the pods are ready I run: `ksync doctor` but I get this error:
```
↳	There is a mismatch between the local version (0.2.6) and the cluster ().

Run 'ksync init --upgrade' to fix.
```
Please see this `CircleCi` run under section: `Install ksync on both client and cluster`:
https://circleci.com/gh/IntelAI/mlt/1672

**Comment by timfallmk** [comment]
@ashahba @bilalbayasut As mentioned elsewhere, this appears to be a weird race condition that we haven't been able to pin down.

For now the fix is to specify the image you want to deploy with `ksync init --image vaporio/ksync:0.2.6` (for example). I should add this to the readme until it's fixed.

**Comment by michalschott** [comment]
This is still happening in all 0.3.X versions.
