### ISSUE TITLE
Error in initializing ksync

### ISSUE THREAD

**Issue by CamiloValderruten** [vapor-ware/ksync#219]
Error:

==== Local Environment ====
Fetching extra binaries                     ✘
↳	no matching assets in this release (v0.14.49)
FATA[0000]

Version:

ksync:
	Version:    Release
	Go Version: go1.10.3
	Git Commit: d2c6365
	Git Tag:    0.3.0
	Built:      Mon Jul 23 23:55:07 +0000 2018
	OS/Arch:    darwin/amd64
service:
	Version:    Release
	Go Version: go1.10.3
	Git Commit: d2c6365
	Git Tag:    0.3.0
	Built:      Mon Jul 23 23:52:07 +0000 2018

**Comment by timfallmk** [comment]
Uh oh, looks like `syncthing` might be fucked up

**Comment by timfallmk** [comment]
Found the issue. https://github.com/syncthing/syncthing changed their release name structure. Update incoming.

**Comment by ashahba** [comment]
@timfallmk would you mind patching the latest release now that the fix is in?

**Comment by s1113950** [comment]
We're testing with latest release and still having issues :/
We get latest release this way:
```
get_latest_release() {
    curl --silent "https://api.github.com/repos/$1/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
}

wget --quiet https://github.com/vapor-ware/ksync/releases/download/$(get_latest_release vapor-ware/ksync)/ksync_${HOST_OS}_${HOST_ARCH} \
    -O $TARGET_INSTALL_PATH/ksync
```
Full install script is here:
https://github.com/IntelAI/mlt/blob/master/scripts/ksync_install.sh
Any help would be appreciated @grampelberg 😄

**Comment by ashahba** [comment]
@timfallmk and @grampelberg would you guys be able to peg `syncthing` to a version like `v0.14.48` rather than pulling latest release so that thing don't break outside of your control? and then only periodically upgrade once it's fully tested.
I've certainly been hit by this many times in my career 🙂

**Comment by ashahba** [comment]
It certainly looks like `ksync` pods take a longer to start now:
```
ksync-24c69                                                      0/2       ContainerCreating   0          6m
ksync-74lwl                                                      2/2       Running             0          7m
ksync-7bs28                                                      2/2       Running             0          6m
ksync-kmrb8                                                      2/2       Running             0          7m
ksync-n9hzn                                                      2/2       Running             0          6m
```
I'm deploying `ksync` on a cluster on `GKE` with only `5` nodes, but 7 minutes through the `init` and one pod is still hanging  and of course my build fails, since I'm only waiting `5` minutes for the pods to be ready.

I've increased the wait time to 10 minutes now and we'll see how it goes.

**Comment by grampelberg** [comment]
Well damn, I'll do some more testing in the morning. Pinning is a great
idea, so we'll get that going as well. Thank you for being understanding!!

**Comment by timfallmk** [comment]
@s1113950 What error are you seeing exactly?

**Comment by CamiloValderruten** [comment]
@grampelberg Thank you!

**Comment by s1113950** [comment]
@timfallmk here's a link to the failed `ksync` install step: https://circleci.com/gh/IntelAI/mlt/1738?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link and the script we use is what I pasted above. We allowed for more time for ksync to install and that did it though so I think we might be good now.
