### ISSUE TITLE
ksync doesn't work

### ISSUE THREAD

**Issue by zkf9971** [vapor-ware/ksync#225]
I install ksync by command "go get github.com/vapor-ware/ksync/cmd/ksync" on the macOS 10.13.3 , but always get "Killed: 9" when I run any commands of ksync, and it exit immediately with "Killed: 9".

go version is go1.9.3 darwin/amd64

**Comment by timfallmk** [comment]
@zkf9971 You may have downloaded the wrong binary. Instead of building it, I would recommend just grabbing the newest binary from the releases page.
