### ISSUE TITLE
Lots of tmp files showing up

### ISSUE THREAD

**Issue by fahanson** [vapor-ware/ksync#232]
Working inside of a git directory that is being synced into a container for development. When going to look at files for the commit I am finding a ton of `.syncthing.*.tmp` files. 

I'm wondering if this was due to a failed sync at some point and they were not cleaned up?

**Comment by timfallmk** [comment]
@fahanson That's entirely possible. A quick search of the synching issues shows they are kept around if the transfer for that specific file didn't complete for any reason. I'm guessing you should be able to safely remove them.
