### ISSUE TITLE
ksync init fails for me on 0.3.2 with Minikube, complaining about docker client version

### ISSUE THREAD

**Issue by johnmcollier** [vapor-ware/ksync#235]
ksync init fails for me on v0.3.2 with Minikube, showing the following error:
```
==== Preflight checks ====
Cluster Config                              ✓ 
Cluster Connection                          ✓ 
Cluster Version                             ✓ 
Cluster Permissions                         ✓ 

==== Cluster Environment ====
Adding ksync to the cluster                 ✓ 
Waiting for pods to be healthy              ✓ 

==== Postflight checks ====
Cluster Service                             ✓ 
Service Health                              ✓ 
Service Version                             ✓ 
Docker Version                              ✘ 
↳	rpc error: code = Unknown desc = Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.35
FATA[0001]                                              
```

If I move back down to 0.3.1, the error goes away. Is there anything else I need to do to get ksync 0.3.2 to work with Minikube?

I've been able to reproduce on two separate Minikube installations, as well as on IBM Cloud Private 3.1

**Comment by timfallmk** [comment]
That's interesting. I was hoping these things might come out before it was released, but it's likely due to the upgraded docker library in `0.3.2`. I'll look at it, but `0.3.2` doesn't have any different features from `0.3.1`, so feel free to use that for the moment.

**Comment by timfallmk** [comment]
Additionally, you can skip the checks to get `0.3.2` running if you want.

**Comment by timfallmk** [comment]
@johnmcollier Could you give me `docker info` from both your local client and the k8s clients?
The important bits will be the supported API versions.

**Comment by timfallmk** [comment]
@johnmcollier Could you give this branch (https://github.com/vapor-ware/ksync/tree/client-version-negotiation) a test? I'll attach some binaries to this comment when they finish building.

**Comment by johnmcollier** [comment]
Hi @timfallmk

Thanks for the binaries! I gave them a try and `ksync init` worked properly:
```
Johns-MacBook-Pro-3:microprofile-x johncollier$ ksync init
==== Preflight checks ====
Cluster Config                              ✓ 
Cluster Connection                          ✓ 
Cluster Version                             ✓ 
Cluster Permissions                         ✓ 

==== Cluster Environment ====
Adding ksync to the cluster                 ✓ 
Waiting for pods to be healthy              ✓ 

==== Postflight checks ====
Cluster Service                             ✓ 
Service Health                              ✓ 
Service Version                             ✓ 
Docker Version                              ✓ 
Docker Storage Driver                       ✓ 
Docker Storage Root                         ✓ 

==== Initialization Complete ====
```

Do you still want the `docker info` from the local and k8s client?

**Comment by timfallmk** [comment]
No worries @johnmcollier! I think this should solve it. I’ll release a new point version to incorporate the change
