### ISSUE TITLE
[FATAL ERROR] CAnnot run ksync run --daemon

### ISSUE THREAD

**Issue by bilalbayasut** [vapor-ware/ksync#246]
Hi guys, I can't run `ksync run --daemon` and it shows this error :
```
WARN[0000] This may be due to config changes. Check Release Notes for anyupdates
FATA[0000] 1 error(s) decoding:

* 'Selector': source data must be an array or slice, got string
```

any idea how to solve that ?

**Comment by timfallmk** [comment]
@bilalbayasut I don't believe there is a `ksync run` command. What version are you using?

**Comment by bilalbayasut** [comment]
Sorry I meant ksync watch --daemon

**Comment by bilalbayasut** [comment]
I'm using Ubuntu 18.04 , minikube , and 0.3.2-hotfix version. I'm afraid ksync gets stuck on pods setting error. but the problem is, I can't see or touch any settings at all.. stuck in that fatal error

**Comment by timfallmk** [comment]
If you try running it without daemonizing (i.e. just `ksync watch`) and turn on debug logging with `--log-level=debug` see if that gives you a different result. I'd have to know more about where the issue occurs before I can help.

**Comment by timfallmk** [comment]
I'm going to close this for now. Feel free to reopen it if you want to.
