### ISSUE TITLE
ksync syncthing keeps syncing the same folders

### ISSUE THREAD

**Issue by scones** [vapor-ware/ksync#248]
Hello ksync developers,

i am currently observing (apart from the other ticket) a phenomena, where the syncthing keeps syncing the a folder, allthough there are no changes locally nor remotely.

i currently use ksync with `--local-read-only`, thus i'd expect no test of remote changes at all.

observing the syncthing logs, i see tons of lines like this:
```
[A6ZLD] 12:10:33 VERBOSE: Remote change detected in folder "smooth-leopard-pontos-app-c5d75888-2xp6x": modified file vendor/symfony/dependency-injection/Compiler/DecoratorServicePass.php
```

followed by tons of lines like this:
```
[A6ZLD] 12:10:33 VERBOSE: Started syncing "smooth-leopard-pontos-app-c5d75888-2xp6x" / "vendor/sebastian/global-state/tests/SnapshotTest.php" (metadata file)
[A6ZLD] 12:10:33 VERBOSE: Finished syncing "smooth-leopard-pontos-app-c5d75888-2xp6x" / "vendor/sebastian/global-state/tests/SnapshotTest.php" (metadata file): Success
```

(random examples from the logs. if i'd search, i'd find a matching pair.)

**Comment by timfallmk** [comment]
@scones The wording might be a little ambiguous but `--local-read-only` _writes_ no changes to the local folder. It will still read and write to the remote end. Is this the behavior you wanted?

Additionally, it looks like the syncing happening is to keep *state* up to date locally. Can you verify if changes are being written to locally? Maybe create a new file on the remote and see if it shows up. My understanding is that those metadata files are what Syncthing uses to track matching state, regardless of whether the file is replicated or not.

**Comment by scones** [comment]
@timfallmk it is, in part, the behaviour i wanted. I wanted the local folder to be the source and the remote to be the target.

The files, syncthing assumes to be changed, are in fact unchanged. Those are external, pre-bundled libraries (hence `vendor`), that are not written or changed. Yet they are synced over and over again.

I do not have a problem with a sync from the remote to my local. My problem is with the endless loop of syncing initiated on the remote for unchanged files. I wouldn't even care that much for that if it weren't preventing the sync of the actually locally changed files to the remote.

**Comment by timfallmk** [comment]
So, to reiterate, although sync events are being triggered, remote files are not being written locally. Is that correct?

This could be an edge case with how one-way syncing is achieved. One-way syncing _to_ the remote (i.e. when changes to the local are copied to the remote and changes to the remote are not copied to the local) is done by ignoring write operations on the local side. This may cause "file changed" messages to still be emitted from the remote side, which is probably what you're seeing. Why that would cause changes not to be mirrored properly is something else.

Could you give me a bit more info on what the sequence of events? Are you writing files locally, seeing the correct messages being emitted, then failing to see those files written remotely? This could also have something to do with your previous issue (#247) and how you're using minikube.

**Comment by scones** [comment]
hello timfallmk,


i will try to take notes when next trying to use ksync. i will get back to you in the next few days with updates.

**Comment by timfallmk** [comment]
Feel free to reopen if needed.
