### ISSUE TITLE
Ksync support for NFS?

### ISSUE THREAD

**Issue by johnmcollier** [vapor-ware/ksync#251]
Does Ksync currently support syncing to Persistent Volume mounts that use NFS? 

I've been having troubles syncing to a folder on a pod that's mounted from an NFS server, and if I sync to any folder off of the volume mount, it syncs fine.

**Comment by timfallmk** [comment]
@johnmcollier Unfortunately ksync doesn't work with k8s persistent volumes at the moment. The short story on that is that, with the current architecture, we can only interact with volumes managed directly by the docker daemon.
