### ISSUE TITLE
Allow for alternative to full container restart

### ISSUE THREAD

**Issue by jensenbox** [vapor-ware/ksync#255]
While a full container restart is very effective, some application development workflows would greatly benefit from a soft reload for the sake of startup time. For example, a large rails app could instead get some variety or a signal or perhaps an HTTP request indicating that it needs to hot reload.

The cleanest solution would be to send a signal to the container in the same way as mentioned https://docs.docker.com/engine/reference/commandline/kill/ - SIGUSR1 for example.

Alternatively, a URL or port to issue an HTTP request to could work. Perhaps an external command line to run every time a sync completes?

**Comment by timfallmk** [comment]
How would you propose this be defined? Since k8s doesn't (AFAIK) have a "soft reload" mechanism built in, it would be somewhat arbitrary.

**Comment by timfallmk** [comment]
I'll close this for now. Feel free to reopen if needed.

**Comment by jensenbox** [comment]
Funny you should ping on this. We have been thinking about how we would do this internally. We have resumed work on our dev environment setup with k8s. We are considering a wrapper to rails that would expose a second port and just restart the child process - but what we don't have is on the client side an event to call out to a curl to hit that nor the config as to what the url of the container is.

Any thoughts on that?

**Comment by jensenbox** [comment]
Are you in SF by any chance?

**Comment by timfallmk** [comment]
@jensenbox Have you considered making use of a sidecar container (like an `initContainer`) to manage the restart/reload? If you wanted to make it really fancy you could register a web hook associated with your deployment/pod/etc. to initiate it.

Yes I am in San Francisco 😄
