### ISSUE TITLE
ksync init fails on Windows

### ISSUE THREAD

**Issue by BarryDrez** [vapor-ware/ksync#267]
When I run ksync init from Windows, I get the following:
```
C:\_Files\ksync\ksync-0.3.4>ksync init
==== Local Environment ====
                                              Fetching extra binaries                     √

==== Preflight checks ====
                                              Cluster Config                              √
                                              Cluster Connection                          √
                                              Cluster Version                             √
                                              Cluster Permissions                         √

==== Cluster Environment ====
                                              Adding ksync to the cluster                 √
                                              Waiting for pods to be healthy              ?
←[31m?←[0m      Timed out waiting for the ksync daemonset to be healthy.

To debug, you can:
- Run 'kubectl --namespace=kube-system --context= get pods -lapp=ksync' to look at what's going on.
- Run 'ksync doctor' to do an in-depth check of your system and the cluster.
time="2019-02-12T07:44:30-05:00" level=fatal
```

I just downloaded and built with the latest source.  It works fine from Linux using the same cluster.  
'kubectl --namespace=kube-system --context= get pods -lapp=ksync' returns:

```
NAME          READY   STATUS             RESTARTS   AGE
ksync-j2xzq   2/2     Running            0          16m
ksync-kgjr5   0/2     ImagePullBackOff   0          2m29s
ksync-w669c   2/2     Running            0          16m
```

 'ksync doctor' returns: 
```
                                              Extra Binaries                              √
                                              Cluster Config                              √
                                              Cluster Connection                          √
                                              Cluster Version                             √
                                              Cluster Permissions                         √
                                              Cluster Service                             √
                                              Service Health                              ?
←[31m?←[0m      Cluster service is not healthy.
```
I have used the same cluster for the Linux client (where it works) and the Windows client.

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

Using Windows 7 Professional
64-bit OS

**Comment by BarryDrez** [comment]
Some more info:

`ksync-j2xzq                               2/2     Running        0          35m

ksync-krdl9                               0/2     ErrImagePull   0          62s

ksync-w669c                               2/2     Running        0          35m`

Looks like a problem pulling an image?

**Comment by timfallmk** [comment]
@BarryDrez Quick side note, typically you'll want to format your code blocks for easy reading, which can be done by enclosing them in triple backticks (``` and ```). Just a note to help with clarity.

It does look like an error pulling the image, but you'll need the actual error to determine why.
`kubectl describe pod ksync-krdl9` will probably get you what you want.

**Comment by BarryDrez** [comment]
Thank you @timfallmk  I am redeploying, and I will get you that information asap.

**Comment by BarryDrez** [comment]
I am having problems building ksync on Windows, so I am unable to reproduce this issue.  May create a new one later if/when I can build again and the problem persists.  Switching to Linux and closing this issue.

**Comment by timfallmk** [comment]
@BarryDrez Are you trying to compile it? You should be able to download and run the binary straight from the release page.

As a side note, we don't have many people testing the windows release, so I'd be happy to hear about any problems you're running into.
