### ISSUE TITLE
Question about Ksync

### ISSUE THREAD

**Issue by BarryDrez** [vapor-ware/ksync#269]
I am reading this blog https://kubernetes.io/blog/2018/05/01/developing-on-kubernetes/
which talks about ksync.  Under Implications, it states that "Container is restarted each time remote filesystem is updated".  I'm probably asking the obvious here, but does this mean that whenever a file is added, changed or deleted from the directory that I am watching within the pod's container, the pod will be restarted?

**Comment by timfallmk** [comment]
@BarryDrez Yes that's correct, although you can disable that behavior with the `--restart=false` flag. `<local|remote-read-only>` may also be of use to you

**Comment by BarryDrez** [comment]
Thank you @timfallmk.  I used --restart=true, and it is no longer restarting.  I want my remote and local directories to be writable, so I should not have to use local-read-only and/or remote-read-only, right?

**Comment by timfallmk** [comment]
@BarryDrez I assume you mean `--restart=false`. The default behavior is `rw`, so you only need to specify those flags if that's **not** what you want

**Comment by BarryDrez** [comment]
Oops.  Yes - --restart=false.
