### ISSUE TITLE
support using cri-o

### ISSUE THREAD

**Issue by damoon** [vapor-ware/ksync#274]
the cluster i use runs on https://cri-o.io/ / https://github.com/kubernetes-sigs/cri-o.
crio is a replacement for docker.
the nodes do not have /var/lib/docker or a docker socket.

how strong is ksync coupled to docker? could it run using kubernetes api features only?

**Comment by timfallmk** [comment]
@damoon Right now `ksync` only works with docker managed volumes, but as has been said elsewhere, a rearchitecture to use Kubernetes managed volumes is possible.

**Comment by bhack** [comment]
Partially overlap with https://github.com/vapor-ware/ksync/issues/265

**Comment by grampelberg** [comment]
@damoon I don't expect a ton of work, but ksync does rely pretty heavily on overlayfs and having a tool to figure out where that directory is. If there was a better way to get that (k8s config, install option) it would be an awesome improvement.

**Comment by timfallmk** [comment]
Closing this for tracking elsewhere.

**Comment by bhack** [comment]
Elsewhere where?
