### ISSUE TITLE
Choose where to run init DaemonSets. 

### ISSUE THREAD

**Issue by machine424** [vapor-ware/ksync#275]
I cannot deploy daemonsets in namespace `kube-system`, while running `ksync init`we can specify the namespace using `--namespace` but I think it doesn't concern daemonsets. 
Is there a way to do so or is it hardcoded ?

I think it's hardcoded in some places, for example for the service representing the daemonset (pkg/ksync/cluster/service.go):
```
func NewService() *Service {
	return &Service{
		Namespace: "kube-system",
```
and the daemonset inherits the same namespace as well (pkg/ksync/cluster/daemon_set.go):
```
func (s *Service) daemonSet() *v1beta1.DaemonSet {
	return &v1beta1.DaemonSet{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: s.Namespace,
```

Is there a reason for that ?

**Comment by timfallmk** [comment]
@machine424 `--namespace` is actually a global flag for operating on specs, it's a little confusing that it appears there too. The daemonsets are hardcoded just for convenience since most users won't have to deal with them at all. If you want to change them now, you can deploy them and then patch. It's not ideal, I know, but there's actually an open issue for changing the way all of that works anyway. #266

**Comment by machine424** [comment]
@timfallmk, thank you for your response. Yes, but it is said that `--namespace`will override the default namespace which is `default` and since we know that DaemonSets are deployed in `kube-system` we are sure they're concerned. I can't deploy anything in `kube-system`, the only solution left, I think, is to change it in the code and recompile it. I'm not familiar with go, I'll try to make a proposition to remove the hardcoded value.

**Comment by timfallmk** [comment]
It wouldn't be difficult to make it changeable upon `init`. It would also be easy for you to recompile with the value you want [here](https://github.com/vapor-ware/ksync/blob/master/pkg/ksync/cluster/service.go#L50-L51). I'll poke around a bit today and see if I can add that functionality.
