### ISSUE TITLE
readme precisions

### ISSUE THREAD

**Issue by sgandon** [vapor-ware/ksync#278]
hello,
in the start guide explained in the readme and katacode is says
```
12) Take a look at the status now. It should be reloading the remote container.
ksync get
```
What does this means exactly cause I don't see neither the pod nor the container restart but this is just the python runtime watching for changes and hot reloading the change.
The way it is written make think that ksync automatically restarts the kuberenetes container.
Or did I miss something?

**Comment by timfallmk** [comment]
@sgandon by default, the target remote container is reloaded upon change. You can change this behavior if you like with the `--reload=<true/false>`.

**Comment by sgandon** [comment]
in the katacoda and even on my machine the container is never restarted.
checking on `kubectl describe mypod` the `Restart Count:  0` is alway to 0.
So this means the container is not restarted.
