### ISSUE TITLE
Not working with two containers in same pod

### ISSUE THREAD

**Issue by raulpuente** [vapor-ware/ksync#279]
Not working with two containers in same pod.

I'm using docker for mac with kubernetes and i'm trying to work with ksync in local, because of performance of docker-for-mac with hostpath.

As explained in https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/ to communicate between to containers in same pod we have to use a volume with emtpyDir.

But when i'm trying to use it with ksync it doesnt works. Seems that it's working, but when i'm going to the directory inside the containers it continues empty. But if i go to one container and touch a file , i see it in the two containers.

Thank you.

**Comment by timfallmk** [comment]
@raulpuente `ksync` doesn't interact with volumes managed by Kubernetes directly (as in this case). It only values managed by Docker.

**Comment by raulpuente** [comment]
Thank you for the information tim.
