### ISSUE TITLE
Ksync files watch needs to be restarted

### ISSUE THREAD

**Issue by alok87** [vapor-ware/ksync#283]
Ksync watch needs to be restarted for it to pick a new `spec` 
if i have started a ksync watch and then i create a spec it sometimes does not pick up changes and pick up and starts sync only after i restart `ksync watch`

✋ i can work on fixing this(if there is an issue) if given some help

**Comment by alok87** [comment]
Not able to reproduce will reopen when see it again

**Comment by alok87** [comment]
Yes i changed the selector in ksync yaml and it did not pick up my pod. I had to restart for changes to be picked up by the watch

**Comment by timfallmk** [comment]
@alok87 It's not really designed for editing of the status files under the hood, generally you would need to delete and re-add the spec via the cli.

**Comment by alok87** [comment]
Is it a good thing to have? any issues you see if we it auto reloads spec list based on yaml change?

**Comment by grampelberg** [comment]
I believe it is listening for file changes though, https://github.com/vapor-ware/ksync/blob/master/cmd/ksync/watch.go#L72

**Comment by alok87** [comment]
It is not working sometimes. I would try to reproduce this and come back.

**Comment by timfallmk** [comment]
I'll close this for now. Reopen if you see it again.
