### ISSUE TITLE
Ksync watch crashes quite often after few minutes run

### ISSUE THREAD

**Issue by alok87** [vapor-ware/ksync#285]
I was running `ksync watch` in foreground and it keeps crashing and have to manually restart it.

Crash is always due to some connection error that happens.
```
ERRO[0299] lost connection to cluster                    ContainerName= 
LocalPath=/home/ubuntu/www/topaz LocalReadOnly=false Name=on-rodent Namespace=local Pod= Reload=false RemotePath=/topaz RemoteReadOnly=false Selector="[version=ad429a7-20190415-052641]"
```

- Please suggest what could be the reason?
- Can we add some auto restart in case of connection failures instead of aborts that happen. We can abort it when there have been n restarts due to connection issues in certain time or we should leave this for the user to manage by some other `systemd` or `supervisor` process?

**Comment by timfallmk** [comment]
Looks like you have a shaky connection to your cluster. The connection code has to maintain sockets and does do re-tries before failing. As you saw, cycling the process recreates the connection, so placing it under process management should give you more resiliency in this case.

**Comment by alok87** [comment]
I see the time to crash after a exact interval. Is it because of some configuration issue in Kubernetes. Something automatically times out and closes connection? Like `kubectl exec` has a timeout which kicks you out of shell.

I am in AWS, provisioned the cluster using kops.

**Comment by timfallmk** [comment]
Hmm, good question. It would be hard to say what it is exactly without looking at your setup.

**Comment by alok87** [comment]
Happening in many in our company. Any way i can print some error in code and find out the reason for loss? Anyway to debug?

**Comment by timfallmk** [comment]
That makes sense, you may want to look at some of the other issues/docs that address this. TL;DR is that you might want to use a process supervisor.

Related to the final point here https://github.com/vapor-ware/ksync#troubleshooting

**Comment by alok87** [comment]
@timfallmk @grampelberg Around 30 developers are using ksync for local development. And every one of them have complained about the crash. We should really find the root cause and fix it. 
```ERRO[0505] lost connection to cluster                    ContainerName= LocalPath=/Users/alok87/code/practo/heimdall LocalReadOnly=true Name=heimdall Namespace=bug Pod= Reload=false RemotePath=/www/app RemoteReadOnly=false Selector="[product=heimdall]"```

**Comment by grampelberg** [comment]
I'd bet that there's something related to keep-alive and how you've got the connection configured to your remote cluster. ksync isn't doing anything special with that connection, so maybe some looking around at client-go watches getting timed out would help?

The easiest solution to this is what @timfallmk suggests - just have the OS restart watch. It was kinda meant to do that to begin with. If you're on OSX, `watch` can be added to launchctl or systemd if you're on linux.
