### ISSUE TITLE
Ksync does not sync nothing

### ISSUE THREAD

**Issue by paullaffitte** [vapor-ware/ksync#290]
Hello, I have an issue with Ksync where it says that it has updated my pod, but in fact it didn't...

```
INFO[0542] updating                                      pod=admin-595c486fdd-b598h spec=busy-cobra
INFO[0542] update complete                               pod=admin-595c486fdd-b598h spec=busy-cobra
INFO[0542] issuing reload                                pod=admin-595c486fdd-b598h spec=busy-cobra
INFO[0542] reloaded                                      pod=admin-595c486fdd-b598h spec=busy-cobra
```

After that my pod is not updated neither restarted.

Sometimes it works and sometimes I have to relaunch `ksync watch` 10 times before it works for real.

EDIT: After some tests, I found that ksync lose control when I introduce an error in my code, then the pods begin a restart loop, because the server crashes as soon as it starts. Then I fix my mistake, and Ksync don't sync anymore my pod, and my files get restored like they were before ksync started to watch.

**Comment by timfallmk** [comment]
Could you tell me more about what you did to "fix" it? It sounds like the files on the local side are overwriting the remote, which is the expected behavior if they're newer.

**Comment by timfallmk** [comment]
I'm going to close this for now. Feel free to open again if it pops up.
