### ISSUE TITLE
Ksync image name is broken and unable to be recovered

### ISSUE THREAD

**Issue by alexanderrtaylor** [vapor-ware/ksync#291]
Issue:
After using ksync(and potentially not stopping the running ksync instances) the command line version of ksync was updated. Now with the newer version the image name is just `vaporio/ksync:git- ` so it looks like [this line](https://github.com/vapor-ware/ksync/blob/fe9ac9d1cab88624fb34e30675242fe83a7121d3/Makefile#L3) is not coming back with data even though when a ksync version is run it looks like this:

`ksync version 
ksync: 
Version: Release 
Go Version: go1.12.1 
Git Commit: c27ce95 
Git Tag: 0.3.6 
Built: Mon Mar 18 17:06:42 +0000 2019 
OS/Arch: darwin/amd64 
FATA[0002] no healthy nodes found `

This causes all the pods to fail to initialize since the image can not be found.

What I have tried:
1. Re-initializing the ksync process
2. removing the pods and allowing them to re-generate
3. stopping the ksync and starting it again
4. Trying to initialize with a specific image(it does not use the image flag given so `ksync init --image=vaporio/ksync:0.3.6` was run but it does not use that image name at all and instead leaves it as before)
5. Deleted the config files with `ksync clean --nuke` and then re-initialized but it still pulled the old non existing image name

Is there some other file I need to be looking for which could cause this issue? Also why does the manual initialize not work?

**Comment by timfallmk** [comment]
I suspect this is due to the loss of a CI environment we had recently. I'll look into fixing the issue, but it _should_ be able to use the last viable tag.
Can you try the following:
```
ksync clean --nuke
kubectl --namespace kube-system get ds ksync
```
There should be no `daemonSet` for `ksync` there, or it should be deleting.
Then:
```
ksync init --image vaporio/ksync:0.3.5
```
Give it time to start up.
See if that gives you a different result.

**Comment by timfallmk** [comment]
Ping @grampelberg

**Comment by alexanderrtaylor** [comment]
@timfallmk it appears that the cause was different versions of Helm installed which meant that dependencies(including ksync) from another command line tool were overriding the ksync commands(I think). It is very strange that the `ksync clean --nuke` did not work though....

I think you can close this

**Comment by timfallmk** [comment]
Oh weird. I assume the "other tool" was `jx`.

The only remote things that `clean` does is remove the configured `daemonSet`. It looks for that based on the configuration in the config file.
