### ISSUE TITLE
Ksync binary download is too slow

### ISSUE THREAD

**Issue by alok87** [vapor-ware/ksync#292]
downloading file from `curl https://vapor-ware.github.io/gimme-that/gimme.sh | bash`
is very slow a lot of times. Takes about 5-10 minutes
please take a look at this.

every other file download is super fast(of same size - but this is very slow)

but could be the internet problem also (i may be too far from the server)

**Comment by timfallmk** [comment]
If you look at that script it simply pulls from github, so nothing here we can do if it's slow.

Alternatively you can try `go get -u -v github.com/vapor-ware/ksync/cmd/ksync` which clones and builds locally, but it should be the same.
