### ISSUE TITLE
ksync - not working across multiple node-pools?

### ISSUE THREAD

**Issue by cyrildiagne** [vapor-ware/ksync#314]
I have 2 node-pools on Google Kubernetes Engine.
A default one and another one with GPUs.
Ksync works well when the pod I want to sync is scheduled on the default node-pool (where the ksync pod is running).
But when my pod is running on the other node-pool, ksync seems stuck in "starting" and doesn't sync.

I run ksync watch in background but get this error after a while:

```
ERRO[0095] (connection.go:99): ksync pod on gke-gpu-sh-k80-ba68a9f2-xqkq not ready  ContainerName= LocalPath=/home LocalReadOnly=false Name=golden-peacock Namespace=default Pod= Reload=false RemotePath=/app_home RemoteReadOnly=false Selector="[app=gpu-dev]"
```

Any idea what could be the problem?

**Comment by grampelberg** [comment]
Hmm, are you using node taints? If the daemon set isn't scheduled on those nodes, ksync won't run.

**Comment by cyrildiagne** [comment]
Oh yes, GKE automatically adds a node taints NoSchedule on `nvidia.com/gpu=present`.
Is there a way to add a toleration to the ksync daemonset?

**Comment by grampelberg** [comment]
Not right now. You can edit it after it has been added to the cluster. Alternatively, wiring up a PR should be pretty easy as well.

**Comment by cyrildiagne** [comment]
Ok, makes sense. Thanks a lot for the rapid feedback!

**Comment by cyrildiagne** [comment]
For future references, I could fix the issue in my case by running:
```
kubectl -n kube-system patch daemonset ksync --type merge -p '
{
   "spec": {
      "template": {
         "spec": {
            "tolerations": [
               {
                  "effect": "NoSchedule",
                  "key": "nvidia.com/gpu",
                  "operator": "Exists"
               }
            ]
         }
      }
   }
}
'
```
