### ISSUE TITLE
ksync doesn't work with kubectl 1.16+

### ISSUE THREAD

**Issue by paulocfjunior** [vapor-ware/ksync#315]
Hi, I'm trying to use ksync with the latest kubectl at this moment, but it seems like the DaemonSet creation is not working because [it's using the DaemonSet from extensions resources](https://github.com/vapor-ware/ksync/blob/master/pkg/ksync/cluster/service.go#L187) and it was [deprecated](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals) in this kubectl version.

**Comment by grampelberg** [comment]
@paulocfjunior oh 1.16 .... would you mind doing a quick PR to update the definitions? I can cut a release immediately to get that fixed up.

**Comment by paulocfjunior** [comment]
Hey @grampelberg, humm.. I'm not sure if I can fix it so quickly since I don't have much experience at Go Lang yet... Do you think it would take much time for you or maybe someone else you know to fix it?

**Comment by grampelberg** [comment]
I can maybe get to it next week, but it'll be a little bit =)

**Comment by paulocfjunior** [comment]
Yeah, we can wait for that :smile: 
Thanks!

**Comment by Zaziffic** [comment]
Hi all,

I confirm ksync is not too happy abour kubectl 1.16+ :
```
$ ksync init

==== Preflight checks ====
Cluster Config                              ✓
Cluster Connection                          ✓
Cluster Version                             ✓
Cluster Permissions                         ✓

==== Cluster Environment ====
Adding ksync to the cluster                 ✘
↳	the server could not find the requested resource
FATA[0000]                                              
```

Versions :
 - ksync: 0.3.6
 - kubectl: 1.16.0
 - minikube: 1.4.0

Thank you ahead for the fix !

**Comment by 0sc** [comment]
Anyone on this yet? I can put up a PR with the update

**Comment by 0sc** [comment]
Here's PR: https://github.com/vapor-ware/ksync/pull/316

**Comment by Zaziffic** [comment]
Thank you guys !
I use ksync a lot in my web applications : good job to you all !

**Comment by Zaziffic** [comment]
Any release planned soon please ? Or should I compile it myself ?
Cheers

**Comment by grampelberg** [comment]
@Zaziffic https://github.com/ksync/ksync/releases/tag/0.4.0

**Comment by Zaziffic** [comment]
Thank you so much @grampelberg  !!! Works like a charm !!! So cool...
