### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by pyronicide** [vapor-ware/ksync#87]
Using the release binary, it appears that there are a couple problems currently.

<img width="886" alt="screenshot 2017-12-18 09 11 23" src="https://user-images.githubusercontent.com/47992/34115315-ea0994de-e3da-11e7-9bf3-25b7bec0bc4c.png">

<img width="549" alt="screenshot 2017-12-18 10 04 27" src="https://user-images.githubusercontent.com/47992/34115319-ec348ac0-e3da-11e7-885c-49079b3ad9d8.png">

**Comment by pyronicide** [comment]
@timfallmk just a heads up, there's only a couple blockers to getting `tutorial` merged, so I'll start tackling this one soonish.

**Comment by timfallmk** [comment]
Ill take a look today as well.
